version: "2.2"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: slurm-docker-cluster:${SLURM_VERSION:-19.05.2}
    build:
      context: .
      dockerfile: Dockerfile.compile 
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: slurm-docker-cluster:${SLURM_VERSION:-19.05.2}
    build:
      context: .
      dockerfile: Dockerfile.compile
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    privileged: true 
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - home:/home
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  rstudio:
    image: slurm-docker-cluster:${SLURM_VERSION:-19.05.2}
    build:
      context: .
      dockerfile: Dockerfile.compile
    command: ["rstudio"]
    container_name: rstudio
    hostname: rstudio
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - home:/home
    expose:
      - "6817"
    ports:
      - "8787:8787"
    depends_on:
      - "slurmctld"

  c1:
    image: slurm-docker-cluster:${SLURM_VERSION:-19.05.2}
    build:
      context: .
      dockerfile: Dockerfile.compile
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    privileged: false
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - home:/home
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: slurm-docker-cluster:${SLURM_VERSION:-19.05.2}
    build:
      context: .
      dockerfile: Dockerfile.compile
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    privileged: false
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - home:/home
    expose:
      - "6818"
    depends_on:
      - "slurmctld"




volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  home:

